package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-04T10:36:15.234+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "TransSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TransSoap {

    @WebMethod(operationName = "Transfer", action = "http://tempuri.org/Transfer")
    @RequestWrapper(localName = "Transfer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Transfer")
    @ResponseWrapper(localName = "TransferResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TransferResponse")
    @WebResult(name = "TransferResult", targetNamespace = "")
    public org.tempuri.TransferResponse2 transfer(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        org.tempuri.TransferRequest request
    );
}
