package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-04T10:36:15.254+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "TransAPIExporterService", 
//                  wsdlLocation = "http://mas.shengpay.com/api-acquire-channel/services/trans?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class TransAPIExporterService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "TransAPIExporterService");
    public final static QName TransAPIExporterPort = new QName("http://tempuri.org/", "TransAPIExporterPort");
    static {
        URL url = null;
        try {
            url = new URL("http://mas.shengpay.com/api-acquire-channel/services/trans?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransAPIExporterService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://mas.shengpay.com/api-acquire-channel/services/trans?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransAPIExporterService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransAPIExporterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransAPIExporterService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransAPIExporterService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransAPIExporterService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransAPIExporterService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TransSoap
     */
    @WebEndpoint(name = "TransAPIExporterPort")
    public TransSoap getTransAPIExporterPort() {
        return super.getPort(TransAPIExporterPort, TransSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransSoap
     */
    @WebEndpoint(name = "TransAPIExporterPort")
    public TransSoap getTransAPIExporterPort(WebServiceFeature... features) {
        return super.getPort(TransAPIExporterPort, TransSoap.class, features);
    }

}
